export type MainStackParamList = {
  Dashboard: undefined;
  Coach: { initialMode?: 'Language Coach' | 'Parent Support' | 'Child Mode' };
  Memories: undefined;
  Play: undefined;
  Report: undefined;
  PlayAnalyzer: undefined;
  Storybook: undefined;
  Knowledge: undefined;
  AddJournal: { id?: string } | undefined;
  AddMilestone: { id?: string } | undefined;
  AddGestalt: { id?: string } | undefined;
  AppointmentNote: { id?: string } | undefined;
  Profile: undefined;
  ChildProfile: { profileId?: string } | undefined;
  ChildProfilesList: undefined;
  UserProfile: undefined;
  SpecialistProfiles: undefined;
  AddEditSpecialist: { specialistId?: string } | undefined;
  ProfileSelection: undefined;
};
